name: Update Agenda Tech Database

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Download latest database
        run: python src/scripts/scraping.py

      - name: Rebuild README
        run: python src/scripts/build_readme.py

      - name: Commit updated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update database and README"
          file_pattern: "src/db/database.json README.md"
